// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";



export const metadata = {
  title: "My next app",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
